-- spring_images import for region: desert
-- DB: desertsoak-db (Cloudflare id 89215d24-0939-4268-89f0-bfb4d98268b8)
--
-- Intentionally empty. The previous version of this file held 471 image rows for
-- Idaho/Montana/Wyoming springs, generated while sites/desert/public/springs.json
-- wrongly contained the Rockies dataset. No openverse images have been gathered
-- for the Southwest (UT/NV/AZ) springs yet.
